[[docs]]
  name = "起步"
  weight = 10
  identifier = "prologue"
  url = "/docs/prologue/"

[[docs]]
  name = "文章精选"
  weight = 20
  identifier = "article"
  url = "/docs/article/"

[[docs]]
  name = "关于我们"
  weight = 30
  identifier = "about"
  url = "/docs/about/"

[[docs]]
  name = "帮助"
  weight = 60
  identifier = "help"
  url = "/docs/help/"

[[main]]
  name = "文章精选"
  url = "/docs/article/"
  weight = 10

[[main]]
  name = "关于我们"
  url = "/docs/about/"
  weight = 20

